# Generated by Django 5.1.6 on 2025-05-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='capacidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
