# Generated by Django 5.1.6 on 2025-05-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_aula_clase_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='clase',
            name='numero_alumnos',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='clase',
            name='aula',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='clases.aula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
